name: Build TRfree-OS ISO

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest

    steps:
      - name: Install dependencies
        run: |
          pacman -Sy --noconfirm archiso git

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Copy releng profile
        run: |
          mkdir archiso
          cp -r /usr/share/archiso/configs/releng/* archiso/

      - name: Build ISO
        run: |
          mkarchiso -v archiso

      - name: Upload ISO
        uses: actions/upload-artifact@v4
        with:
          name: TRfree-OS
          path: out/
